### ISSUE TITLE
Printing does not work

### ISSUE THREAD

**Issue by garrett** [flathub/net.cozic.joplin_desktop#1]
When I select File → Print from the menu, nothing happens for a few seconds, and then a small dialog appears saying "Could not print: no valid printers available".

However, I have a network-available printer configured on my system and it is available to other applications, including other flatpaks, such as Firefox. Additionally, even without a printer installed, it should be possible to "print to a file" (basically save it as a PDF), which is in the general printing dialogs of other apps too.

I'm assuming this has to do with flatpak sandboxing.

Right now, I don't see the printing system flag enabled. Even after toggling it with Flatseal, Joplin still doesn't show a print dialog, so fixing this is probably not quite that simple.

**Comment by catsout** [comment]
Actually, I get a same error with appimage version.
But I solved this by add a virtual local printer on host system. 
I use debian and do this by `apt install print-manager`, and go system-print setting then add it.

But the problem is that I can only see "print as pdf", no printers in flatpak version.

**Comment by catsout** [comment]
>Right now, I don't see the printing system flag enabled.

What's printing system flag?

**Comment by catsout** [comment]
So, in my test, the error "Could not print: no valid printers available" is not caused by flatpak sandbox.
If you have free time, you can test it with [appimage](https://github.com/laurent22/joplin/releases/download/v1.6.7/Joplin-1.6.7.AppImage) version

In fact, joplin support expose as pdf directly.

**Comment by catsout** [comment]
>But the problem is that I can only see "print to pdf", no printers in flatpak version.

@tinywrkb your pr fix this for me. But I can only test it with a virtual printer.

**Comment by tinywrkb** [comment]
@catsout Oh, so that change actually did something, it seems to give access to a local CUPS daemon.  
I'm still not sure that this the wanted behavior, I would prefer to get the regular GTK3 print dialog instead of whatever Electron is showing and that it won't fail if CUPS daemon isn't running.  
It too late over here to test actual printing.

**Comment by catsout** [comment]
>I would prefer to get the regular GTK3 print dialog instead of whatever Electron is showing and that it won't fail if CUPS daemon isn't running.

I think it's ok, as it's the same behavior as joplin appimage version.
Other electron app, like typora(flatpak), will not fail without virtual printer, but only show "print to pdf" too.
So, the error "Could not print: no valid printers available", most likely caused by joplin or it's electron dependencies.

**Comment by tinywrkb** [comment]
Right, might be an Electron issue  https://github.com/electron/electron/issues/24664

Other than that, after playing with the GTK `settings.ini` and GTK_PATH environment variable it looks like it's working at it should so I'll reopen the PR.

**Comment by garrett** [comment]
Thanks for fixing this so quickly! (I try not to print, but occasionally it's needed, and it's good to know it's there now.)

---

Also: _Huge thanks for packaging Joplin as a flatpak!_ 💖

I first saw Joplin a few months ago, but didn't install it, as there was no good way to do so on Fedora. (AppImages are horrible security-wise, lack integration, and have no proper way to update... and I try to not compile software I rely on every day from source.) So I was _very_ happy to see Joplin show up in the "new & updated" area of Flathub.

I've imported all my existing notes (from Markdown) and even installed the Android app from F-Droid as a result of your efforts. Thanks again!

**Comment by pxcask** [comment]
> When I select File → Print from the menu, nothing happens for a few seconds, and then a small dialog appears saying "Could not print: no valid printers available".
> 

I am aware that the topic is closed. A simple solution on Ubuntu solved it for me: Goto "Settings - Applications - Joplin" and permit "print documents".
