### ISSUE TITLE
Automatically switch theme to match system theme setting doesn't work on Linux flatpak

### ISSUE THREAD

**Issue by MarkWieczorek** [flathub/net.cozic.joplin_desktop#144]
"Automatically switch theme to match system theme" setting doesn't work on Linux (flatpak version). Changing the system theme does change the color of the menu bar, but that is it, the remainder of the window remains in the "light" mode. I note that the dark theme does indeed work if you manually choose it.

According to the main repo https://github.com/laurent22/joplin/issues/9152, this does indeed work on the snap and AppImage versions, so this seems to be restricted to flatpak. I did try to use flatseal to enable more permissions, but was unsuccessful.

**Comment by danilown** [comment]
You mentioned the issue that you tested the Appimage and the Snap versions on Ubuntu and it worked. Have you tested the flatpak version on Ubuntu as well? If not, could you test it and inform us of the results?

I think the problem is that changing to Dark Style in GNOME only changes the Adwaita theme. You probably need to install [adw-gtk3](https://github.com/lassekongo83/adw-gtk3). At least the flatpak themes.

After installing, try to change to Dark Style. It should work.

If it does not work, try running this command:

```
gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark'
```

**Comment by MarkWieczorek** [comment]
The problem seems to have solved itself without installing the packages you suggested. I am not really sure how this happened, but itis  probably is related to an update of the packages "GNOME Application Platform version 44/45" that occurred a few days ago.  I'll just close this, but if others are encountering this issue, feel free to re-open it.
